CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Auto-incrementing ID
                       username VARCHAR(255) NOT NULL UNIQUE,
                       email VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       first_name VARCHAR(255) NOT NULL, -- First name
                       last_name VARCHAR(255) NOT NULL  -- Last name
);

CREATE TABLE user_followers (
                                user_id BIGINT NOT NULL,
                                follower_id BIGINT NOT NULL,
                                PRIMARY KEY (user_id, follower_id),
                                FOREIGN KEY (user_id) REFERENCES users (id),
                                FOREIGN KEY (follower_id) REFERENCES users (id)
);